In [1]:
import pandas as pd
df = pd.read_csv("weight-height.csv")
df.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
q1 = df.Height.quantile(0.25)
q3 = df.Height.quantile(0.75)
wq1 = df.Weight.quantile(0.25)
wq3 = df.Weight.quantile(0.75)
IQR = q3 - q1
WIQR = wq3 - wq1
upper_limit = q3 + 1.5*IQR
lower_limit = q1 - 1.5*IQR
w_upper_limit = wq3 + 1.5*IQR
w_lower_limit = wq1 - 1.5*IQR

In [5]:
df_with_no_outliers = df[(upper_limit > df.Height) & (df.Height > lower_limit) & (df.Weight > w_lower_limit) & (df.Weight < w_upper_limit)]
df_with_no_outliers

    Gender     Height      Weight
6     Male  68.785081  183.927889
7     Male  68.348516  167.971110
8     Male  67.018950  175.929440
10    Male  71.195382  186.604926
12    Male  64.766329  167.127461
..     ...        ...         ...
143   Male  67.432120  183.508933
145   Male  70.515860  183.759845
146   Male  71.338376  201.954495
150   Male  67.479352  178.618350
152   Male  70.844062  195.937015

[98 rows x 3 columns]